<?php

use Phinx\Seed\AbstractSeed;

/**
 * Universities Seeder
 * Seeds universities available through ApplyBoard, Edvoy, and other partner platforms
 * Focus: UK, Canada, Australia, USA - Popular destinations for Nigerian students
 */
class UniversitiesSeeder extends AbstractSeed
{
    public function run(): void
    {
        // Clear existing data
        $this->execute('DELETE FROM universities');

        $universities = array_merge(
            $this->getUKUniversities(),
            $this->getCanadaUniversities(),
            $this->getUSAUniversities(),
            $this->getAustraliaUniversities()
        );

        $this->table('universities')->insert($universities)->saveData();

        $this->output->writeln('<info>Seeded ' . count($universities) . ' universities successfully!</info>');
    }

    private function getUKUniversities(): array
    {
        return [
            // Top UK Universities on ApplyBoard & Edvoy
            [
                'name' => 'University of Edinburgh',
                'slug' => 'university-of-edinburgh',
                'country' => 'UK',
                'city' => 'Edinburgh',
                'state_province' => 'Scotland',
                'website_url' => 'https://www.ed.ac.uk',
                'ranking' => 15,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 22000,
                'tuition_max' => 35000,
                'currency' => 'GBP',
                'acceptance_rate' => 45.00,
                'min_gpa' => 3.20,
                'min_ielts' => 6.5,
                'min_toefl' => 92,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 14,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Computer Science', 'Business', 'Medicine', 'Engineering']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'University of Birmingham',
                'slug' => 'university-of-birmingham',
                'country' => 'UK',
                'city' => 'Birmingham',
                'state_province' => 'England',
                'website_url' => 'https://www.birmingham.ac.uk',
                'ranking' => 84,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 19000,
                'tuition_max' => 28000,
                'currency' => 'GBP',
                'acceptance_rate' => 55.00,
                'min_gpa' => 3.00,
                'min_ielts' => 6.0,
                'min_toefl' => 80,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 14,
                'edvoy_processing_days' => 12,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Business', 'Engineering', 'Law', 'Medicine']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Coventry University',
                'slug' => 'coventry-university',
                'country' => 'UK',
                'city' => 'Coventry',
                'state_province' => 'England',
                'website_url' => 'https://www.coventry.ac.uk',
                'ranking' => 571,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 15000,
                'tuition_max' => 20000,
                'currency' => 'GBP',
                'acceptance_rate' => 75.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 12.00,
                'applyboard_processing_days' => 7,
                'edvoy_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Business', 'Engineering', 'Computing', 'Health']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'University of Portsmouth',
                'slug' => 'university-of-portsmouth',
                'country' => 'UK',
                'city' => 'Portsmouth',
                'state_province' => 'England',
                'website_url' => 'https://www.port.ac.uk',
                'ranking' => 516,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 14500,
                'tuition_max' => 19000,
                'currency' => 'GBP',
                'acceptance_rate' => 70.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 11.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Business', 'Computing', 'Pharmacy', 'Engineering']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Aston University',
                'slug' => 'aston-university',
                'country' => 'UK',
                'city' => 'Birmingham',
                'state_province' => 'England',
                'website_url' => 'https://www.aston.ac.uk',
                'ranking' => 446,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 16000,
                'tuition_max' => 21000,
                'currency' => 'GBP',
                'acceptance_rate' => 65.00,
                'min_gpa' => 2.70,
                'min_ielts' => 6.0,
                'min_toefl' => 80,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Business', 'Engineering', 'Health', 'Languages']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'University of East London',
                'slug' => 'university-of-east-london',
                'country' => 'UK',
                'city' => 'London',
                'state_province' => 'England',
                'website_url' => 'https://www.uel.ac.uk',
                'ranking' => 801,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 13500,
                'tuition_max' => 15500,
                'currency' => 'GBP',
                'acceptance_rate' => 80.00,
                'min_gpa' => 2.30,
                'min_ielts' => 6.0,
                'min_toefl' => 72,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 12.00,
                'applyboard_processing_days' => 7,
                'edvoy_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Business', 'Computing', 'Psychology', 'Health']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Bournemouth University',
                'slug' => 'bournemouth-university',
                'country' => 'UK',
                'city' => 'Bournemouth',
                'state_province' => 'England',
                'website_url' => 'https://www.bournemouth.ac.uk',
                'ranking' => 651,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 15000,
                'tuition_max' => 18000,
                'currency' => 'GBP',
                'acceptance_rate' => 70.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Media', 'Tourism', 'Business', 'Health']),
                'popular' => false,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'University of Greenwich',
                'slug' => 'university-of-greenwich',
                'country' => 'UK',
                'city' => 'London',
                'state_province' => 'England',
                'website_url' => 'https://www.gre.ac.uk',
                'ranking' => 751,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 14500,
                'tuition_max' => 16500,
                'currency' => 'GBP',
                'acceptance_rate' => 75.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 72,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 11.00,
                'applyboard_processing_days' => 7,
                'edvoy_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Business', 'Computing', 'Engineering', 'Architecture']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Birmingham City University',
                'slug' => 'birmingham-city-university',
                'country' => 'UK',
                'city' => 'Birmingham',
                'state_province' => 'England',
                'website_url' => 'https://www.bcu.ac.uk',
                'ranking' => 801,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 13500,
                'tuition_max' => 16000,
                'currency' => 'GBP',
                'acceptance_rate' => 78.00,
                'min_gpa' => 2.30,
                'min_ielts' => 6.0,
                'min_toefl' => 72,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 12.00,
                'applyboard_processing_days' => 7,
                'edvoy_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Business', 'Art & Design', 'Law', 'Health']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Swansea University',
                'slug' => 'swansea-university',
                'country' => 'UK',
                'city' => 'Swansea',
                'state_province' => 'Wales',
                'website_url' => 'https://www.swansea.ac.uk',
                'ranking' => 425,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 17000,
                'tuition_max' => 22000,
                'currency' => 'GBP',
                'acceptance_rate' => 65.00,
                'min_gpa' => 2.70,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Engineering', 'Science', 'Business', 'Medicine']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
        ];
    }

    private function getCanadaUniversities(): array
    {
        return [
            [
                'name' => 'University of Toronto',
                'slug' => 'university-of-toronto',
                'country' => 'Canada',
                'city' => 'Toronto',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.utoronto.ca',
                'ranking' => 21,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 45000,
                'tuition_max' => 65000,
                'currency' => 'CAD',
                'acceptance_rate' => 43.00,
                'min_gpa' => 3.50,
                'min_ielts' => 6.5,
                'min_toefl' => 89,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 8.00,
                'applyboard_processing_days' => 21,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Computer Science', 'Engineering', 'Business', 'Medicine']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'Western University',
                'slug' => 'western-university',
                'country' => 'Canada',
                'city' => 'London',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.uwo.ca',
                'ranking' => 120,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 35000,
                'tuition_max' => 50000,
                'currency' => 'CAD',
                'acceptance_rate' => 55.00,
                'min_gpa' => 3.00,
                'min_ielts' => 6.5,
                'min_toefl' => 83,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 10.00,
                'applyboard_processing_days' => 14,
                'intake_periods' => json_encode(['September', 'January']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Business', 'Engineering', 'Health Sciences', 'Law']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Trent University',
                'slug' => 'trent-university',
                'country' => 'Canada',
                'city' => 'Peterborough',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.trentu.ca',
                'ranking' => 801,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 22000,
                'tuition_max' => 28000,
                'currency' => 'CAD',
                'acceptance_rate' => 75.00,
                'min_gpa' => 2.70,
                'min_ielts' => 6.5,
                'min_toefl' => 80,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 12.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Environmental Science', 'Business', 'Psychology', 'Biology']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'Lakehead University',
                'slug' => 'lakehead-university',
                'country' => 'Canada',
                'city' => 'Thunder Bay',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.lakeheadu.ca',
                'ranking' => 1001,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 20000,
                'tuition_max' => 28000,
                'currency' => 'CAD',
                'acceptance_rate' => 80.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.5,
                'min_toefl' => 80,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 12.00,
                'applyboard_processing_days' => 10,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Nursing', 'Engineering', 'Business', 'Education']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Algoma University',
                'slug' => 'algoma-university',
                'country' => 'Canada',
                'city' => 'Sault Ste. Marie',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.algomau.ca',
                'ranking' => 1201,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 18000,
                'tuition_max' => 22000,
                'currency' => 'CAD',
                'acceptance_rate' => 85.00,
                'min_gpa' => 2.30,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 12.00,
                'applyboard_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Bachelor']),
                'popular_fields' => json_encode(['Business', 'Computer Science', 'Biology', 'Psychology']),
                'popular' => false,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Conestoga College',
                'slug' => 'conestoga-college',
                'country' => 'Canada',
                'city' => 'Kitchener',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.conestogac.on.ca',
                'ranking' => null,
                'ranking_source' => null,
                'tuition_min' => 15000,
                'tuition_max' => 18000,
                'currency' => 'CAD',
                'acceptance_rate' => 85.00,
                'min_gpa' => 2.30,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 15.00,
                'applyboard_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Diploma', 'Bachelor']),
                'popular_fields' => json_encode(['Engineering Technology', 'Business', 'IT', 'Health']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Seneca College',
                'slug' => 'seneca-college',
                'country' => 'Canada',
                'city' => 'Toronto',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.senecacollege.ca',
                'ranking' => null,
                'ranking_source' => null,
                'tuition_min' => 15000,
                'tuition_max' => 18000,
                'currency' => 'CAD',
                'acceptance_rate' => 80.00,
                'min_gpa' => 2.30,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 15.00,
                'applyboard_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Diploma', 'Bachelor']),
                'popular_fields' => json_encode(['Business', 'IT', 'Animation', 'Aviation']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'George Brown College',
                'slug' => 'george-brown-college',
                'country' => 'Canada',
                'city' => 'Toronto',
                'state_province' => 'Ontario',
                'website_url' => 'https://www.georgebrown.ca',
                'ranking' => null,
                'ranking_source' => null,
                'tuition_min' => 15500,
                'tuition_max' => 19000,
                'currency' => 'CAD',
                'acceptance_rate' => 78.00,
                'min_gpa' => 2.30,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 15.00,
                'applyboard_processing_days' => 7,
                'intake_periods' => json_encode(['September', 'January', 'May']),
                'program_levels' => json_encode(['Diploma', 'Bachelor']),
                'popular_fields' => json_encode(['Culinary', 'Business', 'Health Sciences', 'Design']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
        ];
    }

    private function getUSAUniversities(): array
    {
        return [
            [
                'name' => 'University of Arizona',
                'slug' => 'university-of-arizona',
                'country' => 'USA',
                'city' => 'Tucson',
                'state_province' => 'Arizona',
                'website_url' => 'https://www.arizona.edu',
                'ranking' => 97,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 35000,
                'tuition_max' => 45000,
                'currency' => 'USD',
                'acceptance_rate' => 85.00,
                'min_gpa' => 2.70,
                'min_ielts' => 6.0,
                'min_toefl' => 70,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 10.00,
                'applyboard_processing_days' => 14,
                'intake_periods' => json_encode(['Fall', 'Spring', 'Summer']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Engineering', 'Business', 'Science', 'Health']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'Arizona State University',
                'slug' => 'arizona-state-university',
                'country' => 'USA',
                'city' => 'Tempe',
                'state_province' => 'Arizona',
                'website_url' => 'https://www.asu.edu',
                'ranking' => 179,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 30000,
                'tuition_max' => 40000,
                'currency' => 'USD',
                'acceptance_rate' => 88.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 61,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 10.00,
                'applyboard_processing_days' => 10,
                'intake_periods' => json_encode(['Fall', 'Spring', 'Summer']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Business', 'Engineering', 'Computer Science', 'Journalism']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'Southern New Hampshire University',
                'slug' => 'southern-new-hampshire-university',
                'country' => 'USA',
                'city' => 'Manchester',
                'state_province' => 'New Hampshire',
                'website_url' => 'https://www.snhu.edu',
                'ranking' => 1001,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 15000,
                'tuition_max' => 32000,
                'currency' => 'USD',
                'acceptance_rate' => 90.00,
                'min_gpa' => 2.30,
                'min_ielts' => 6.0,
                'min_toefl' => 71,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 12.00,
                'applyboard_processing_days' => 7,
                'intake_periods' => json_encode(['Fall', 'Spring', 'Summer']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Business', 'IT', 'Healthcare', 'Education']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Kent State University',
                'slug' => 'kent-state-university',
                'country' => 'USA',
                'city' => 'Kent',
                'state_province' => 'Ohio',
                'website_url' => 'https://www.kent.edu',
                'ranking' => 801,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 19000,
                'tuition_max' => 28000,
                'currency' => 'USD',
                'acceptance_rate' => 85.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 71,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['Fall', 'Spring', 'Summer']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Journalism', 'Fashion', 'Business', 'Education']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'University of South Florida',
                'slug' => 'university-of-south-florida',
                'country' => 'USA',
                'city' => 'Tampa',
                'state_province' => 'Florida',
                'website_url' => 'https://www.usf.edu',
                'ranking' => 284,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 17000,
                'tuition_max' => 28000,
                'currency' => 'USD',
                'acceptance_rate' => 45.00,
                'min_gpa' => 3.00,
                'min_ielts' => 6.5,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 10.00,
                'applyboard_processing_days' => 14,
                'intake_periods' => json_encode(['Fall', 'Spring', 'Summer']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Business', 'Engineering', 'Health Sciences', 'Marine Biology']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
        ];
    }

    private function getAustraliaUniversities(): array
    {
        return [
            [
                'name' => 'University of Melbourne',
                'slug' => 'university-of-melbourne',
                'country' => 'Australia',
                'city' => 'Melbourne',
                'state_province' => 'Victoria',
                'website_url' => 'https://www.unimelb.edu.au',
                'ranking' => 13,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 35000,
                'tuition_max' => 50000,
                'currency' => 'AUD',
                'acceptance_rate' => 55.00,
                'min_gpa' => 3.20,
                'min_ielts' => 6.5,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => false,
                'applyboard_commission' => 8.00,
                'applyboard_processing_days' => 21,
                'intake_periods' => json_encode(['February', 'July']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Medicine', 'Law', 'Business', 'Engineering']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'Griffith University',
                'slug' => 'griffith-university',
                'country' => 'Australia',
                'city' => 'Brisbane',
                'state_province' => 'Queensland',
                'website_url' => 'https://www.griffith.edu.au',
                'ranking' => 243,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 28000,
                'tuition_max' => 38000,
                'currency' => 'AUD',
                'acceptance_rate' => 70.00,
                'min_gpa' => 2.70,
                'min_ielts' => 6.5,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 14,
                'edvoy_processing_days' => 14,
                'intake_periods' => json_encode(['February', 'July', 'November']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Business', 'Engineering', 'Health', 'Criminology']),
                'popular' => true,
                'featured' => true,
                'is_active' => true
            ],
            [
                'name' => 'Deakin University',
                'slug' => 'deakin-university',
                'country' => 'Australia',
                'city' => 'Melbourne',
                'state_province' => 'Victoria',
                'website_url' => 'https://www.deakin.edu.au',
                'ranking' => 210,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 30000,
                'tuition_max' => 42000,
                'currency' => 'AUD',
                'acceptance_rate' => 65.00,
                'min_gpa' => 2.70,
                'min_ielts' => 6.0,
                'min_toefl' => 79,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 10.00,
                'edvoy_commission' => 10.00,
                'applyboard_processing_days' => 14,
                'edvoy_processing_days' => 14,
                'intake_periods' => json_encode(['February', 'July', 'November']),
                'program_levels' => json_encode(['Bachelor', 'Master', 'PhD']),
                'popular_fields' => json_encode(['Business', 'IT', 'Sport Science', 'Nursing']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Central Queensland University',
                'slug' => 'central-queensland-university',
                'country' => 'Australia',
                'city' => 'Rockhampton',
                'state_province' => 'Queensland',
                'website_url' => 'https://www.cqu.edu.au',
                'ranking' => 601,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 25000,
                'tuition_max' => 32000,
                'currency' => 'AUD',
                'acceptance_rate' => 80.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 75,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 12.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['February', 'July', 'November']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Engineering', 'Nursing', 'Business', 'Education']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
            [
                'name' => 'Victoria University',
                'slug' => 'victoria-university-australia',
                'country' => 'Australia',
                'city' => 'Melbourne',
                'state_province' => 'Victoria',
                'website_url' => 'https://www.vu.edu.au',
                'ranking' => 551,
                'ranking_source' => 'QS 2025',
                'tuition_min' => 24000,
                'tuition_max' => 32000,
                'currency' => 'AUD',
                'acceptance_rate' => 78.00,
                'min_gpa' => 2.50,
                'min_ielts' => 6.0,
                'min_toefl' => 72,
                'available_on_applyboard' => true,
                'available_on_edvoy' => true,
                'applyboard_commission' => 12.00,
                'edvoy_commission' => 12.00,
                'applyboard_processing_days' => 10,
                'edvoy_processing_days' => 10,
                'intake_periods' => json_encode(['February', 'July']),
                'program_levels' => json_encode(['Bachelor', 'Master']),
                'popular_fields' => json_encode(['Business', 'IT', 'Sport', 'Health']),
                'popular' => true,
                'featured' => false,
                'is_active' => true
            ],
        ];
    }
}
